/*
 *  Copyright (c) 2011 Evgeny Proydakov <lord.tiran@gmail.com>
 */

#ifndef I_IDENTIFICATION_NUMBER_CONFIG
#define I_IDENTIFICATION_NUMBER_CONFIG

#define INPUT_FILE_1 "${CMAKE_CURRENT_SOURCE_DIR}/1.txt"
#define INPUT_FILE_2 "${CMAKE_CURRENT_SOURCE_DIR}/2.txt"
#define INPUT_FILE_3 "${CMAKE_CURRENT_SOURCE_DIR}/3.txt"
#define INPUT_FILE_4 "${CMAKE_CURRENT_SOURCE_DIR}/4.txt"
#define INPUT_FILE_5 "${CMAKE_CURRENT_SOURCE_DIR}/5.txt"
#define INPUT_FILE_6 "${CMAKE_CURRENT_SOURCE_DIR}/6.txt"
#define INPUT_FILE_7 "${CMAKE_CURRENT_SOURCE_DIR}/7.txt"
#define INPUT_FILE_8 "${CMAKE_CURRENT_SOURCE_DIR}/8.txt"
#define INPUT_FILE_9 "${CMAKE_CURRENT_SOURCE_DIR}/9.txt"

#endif // I_IDENTIFICATION_NUMBER_CONFIG
